### ISSUE TITLE
HomeKit not showing individual zones

### ISSUE THREAD

**Issue by dfizzo** [valiquette/homebridge-rachio-irrigation#41] opened 2022-04-19 15:18 UTC
I had zero issues with this wonderful plug-in until recently. All of a sudden, I am seeing blank space where the individual switches for each sprinkler zone used to show up. See below image. Any thoughts? Thanks!!

![image](https://user-images.githubusercontent.com/83602323/164037884-5e235b8c-6415-4656-be04-da16a601a2b3.png)

**Comment by valiquette** [comment] 2022-04-19 16:06
I am seeing the same thing and it seem hit or miss with Apple. I am not sure what changed or what if anything I can do with the plugin. But I will be looking into it.

**Comment by dfizzo** [comment] 2022-04-19 16:17
Thanks @valiquette!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Apr 19, 2022, at 12:06 PM, valiquette ***@***.***> wrote:

﻿
I am seeing the same thing and it seem hit or miss with Apple. I am not sure what changed or what if anything I can do with the plugin. But I will be looking into it.

**Comment by valiquette** [comment] 2022-04-19 20:54
Seems to be a wide spread issue with irrigation system and not just this plugin. I did find a note from someone else that if you long press the tile, not just click it will display correctly and that seems to work for me. Which make sense to now to my earlier comment that it maybe hit or mis.

**Comment by dfizzo** [comment] 2022-04-19 21:38
Thanks. That doesn’t work for me but thanks! Probably an iOS 14.1 update related issue?
________________________________

**Comment by derek-miller** [comment] 2022-04-21 14:54
I too am seeing this with this plugin as well as the native rachio integration. Seems like an Apple issue.

**Comment by valiquette** [comment] 2022-09-13 17:28
Fixed in IOS 16

**Closed by valiquette** 2022-09-13 17:28 UTC

**Comment by cpenrose64** [comment] 2023-06-05 15:18
Hello - I am seeing this issue again in iOS 16.5.  I only see one tile for the sprinkler.  The only way to see each zone is tape the tile.  Is that the current work-around?

**Comment by valiquette** [comment] 2023-06-05 16:25
I am not sure exactly what you are asking about. By default there should be one tile, tap to show all zones. Alternately in the plugin setting you can turn off show as irrigation. Then in homekit show as separate tiles. 
When you did the 16.5 update did you do the home app update too?

**Comment by cpenrose64** [comment] 2023-06-27 00:02
> I am not sure exactly what you are asking about. By default there should be one tile, tap to show all zones. Alternately in the plugin setting you can turn off show as irrigation. Then in homekit show as separate tiles.
> When you did the 16.5 update did you do the home app update too?

Thank you.  It appears to be working as designed.  I am on 16.5 and have done the Home app update when it first came out.
